name: Publish to Nuget

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'

    - name: Checkout Repository
      uses: actions/checkout@v2

    # Restore Tools from Manifest list in the Repository
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run Uno Check to Install Dependencies
      run: dotnet tool run uno-check --ci --fix --non-interactive --skip wsl --skip androidemulator --skip vswinworkloads --verbose

    - name: Restore .NET workloads
      run: dotnet workload restore ./src/OwlCore.Storage.Uwp.csproj

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17.9,)'

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
    - name: MSBuild
      run: msbuild.exe /r

    - name: Run tests
      run:  vstest.console.exe ./tests/**/*.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=UWP.trx"
      
    - name: MSBuild (DebugType Portable)
      run: msbuild.exe /r -p:Configuration=Release -p:DebugType=Portable ./src/
      
    - name: MSBuild Pack
      run: msbuild.exe -t:pack -p:Configuration=Release -p:DebugType=Portable ./src/

    - name: list files
      run: ls ./src/bin/Release/

    - name: Publish to NuGet
      run: dotnet nuget push "**/Release/OwlCore.Storage.Uwp.*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
