name: Publish to Nuget

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - name: Install .NET 6 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.401'

    - name: Checkout Repository
      uses: actions/checkout@v2

    # Restore Tools from Manifest list in the Repository
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run Uno Check to Install Dependencies
      run: dotnet tool run uno-check --ci --fix --non-interactive --skip wsl --skip androidemulator --verbose

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: MSBuild
      run: msbuild.exe /r -p:Configuration=Release

    - name: Run tests
      run:  vstest.console.exe ./tests/**/*.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=UWP.trx"

    - name: Publish to NuGet
      run: dotnet nuget push "/home/runner/work/OwlCore.Storage.Uwp/OwlCore.Storage.Uwp/src/bin/Release/OwlCore.Storage.Uwp.*.*.*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
